server:
  port: 8084
  servlet:
    session:
      cookie:
        name: KSESSION
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:8083/oauth/authorize
      access-token-uri: http://localhost:8083/oauth/token
    resource:
      token-info-uri: http://localhost:8083/oauth/check_token