server:
  port: 8081
spring:
  application:
    name: profile-service
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8083/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin