server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/craigmiller160/practice-spring-cloud-config-store
          username: craigmiller160@gmail.com
          search-paths:
            - '*'
logging:
  level:
    org.springframework.security: DEBUG